
<div id="layerManager">
	<h3>Gestionnaire de claques</h3>
	<?php foreach($this->getLayers() as $key => $layer):?>
	<ul>
		<li>Calque n°<?php echo $key + 1;?></li>		
		<li>Nom du calque : <?php echo $layer->getName()?></li>
		<li>Transparence : <?php echo $layer->getTransparence()?></li>
		<?php if($layer->hasFilter()):?>
		<?php foreach($layer->getFilters() as $name => $filter):?>
				<li>Filtre <?php echo $filter->getName();?></li>			
		<?php endforeach;?>
		<?php endif;?>
	</ul>
	<?php endforeach;?>	
</div>

<script type="text/javascript">
var div = window.document.getElementById('layerManager');
div.style.backgroundColor = 'blue';
div.style.color= 'white';
div.style.height= '100%';
div.style.width= '250px';
div.style.position = 'fixed';
div.style.left = 0;
div.style.top = 0;
var ul = div.getElementByTagsName('ul');
for(var i in ul) {
	var list = ul[i];
	list.style.position = 'relative';
	list.style.display = 'block';
	list.style.margin = '1%';
}
</script>
