<?php 
/** 
 *  Good 1.0
 *
 * @author franckysolo <franckysolo@gmail.com>
 */
 

 /**
 *  Good 1.0
 *
 * @author franckysolo <franckysolo@gmail.com>
 * @since 22 oct. 2012
 * @license license.txt
 * @category Good 
 * @package Good
 * @subpackage Gd
 * @filesource Image.phtml
 * @version $Id: $
 * @desc : the image view class
 */
?>
<figure>
	<img alt="<?php echo $this->getHtmlAttribute('src');?>" src="<?php echo $this->getHtmlAttribute('src');?>" />
	<figcaption><?php echo $this->getHtmlAttribute('figcaption');?></figcaption>
</figure>

